### ISSUE TITLE
Bug Extra IP Address = None 

### ISSUE THREAD

**Issue by ryanpek** [solusio/solusiovps#78]
https://dl.dropboxusercontent.com/s/w89buae321i3i08/chrome_NHi5mGjJEd.jpg

In WHMCS when the Extra IP setting is set to "None" the whmcs module fails to create the VPS.  This should create the VPS with 1 IP. 

TypeError: Argument 1 passed to WHMCS\Module\Server\SolusIoVps\SolusAPI\Requests\ServerCreateRequestBuilder::withAdditionalIps() must be of the type int, string given, called in modules/servers/solusiovps/lib/SolusAPI/Requests/ServerCreateRequestBuilder.php on line 143 and defined in modules/servers/solusiovps/lib/SolusAPI/Requests/ServerCreateRequestBuilder.php:184
Stack trace:
#0 modules/servers/solusiovps/lib/SolusAPI/Requests/ServerCreateRequestBuilder.php(143): WHMCS\Module\Server\SolusIoVps\SolusAPI\Requests\ServerCreateRequestBuilder->withAdditionalIps()
#1 modules/servers/solusiovps/solusiovps.php(300): WHMCS\Module\Server\SolusIoVps\SolusAPI\Requests\ServerCreateRequestBuilder::fromWHMCSCreateAccountParams()
#2 vendor/whmcs/whmcs-foundation/lib/Module/AbstractModule.php(0): solusiovps_CreateAccount()
#3 vendor/whmcs/whmcs-foundation/lib/Module/Server.php(0): WHMCS\Module\AbstractModule->call()
#4 includes/modulefunctions.php(0): WHMCS\Module\Server->call()
#5 vendor/whmcs/whmcs-foundation/lib/Service/Service.php(0): ModuleCallFunction()
#6 includes/orderfunctions.php(0): WHMCS\Service\Service->legacyProvision()
#7 dashboard/orders.php(0): acceptOrder()
#8 {main}

**Comment by ryanpek** [comment]
If you want 0, it has to be set like this:
![image](https://user-images.githubusercontent.com/23507105/184633321-89777791-f720-45b2-8600-112c454c049f.png)
